function [CenterFreq,SymbolRate,FEC,path,DemodMod,nfwdweights,nfbkweights,constant1,constant2]=RECIEVER_GUI()
    d = dialog('Position',[550 300 260 320],'Name','Reciever Settings');
     uicontrol('Parent',d,...
               'Style','text',...
               'Position',[0 290 265 20],...
               'String','Settings For Reciever',...
               'FontSize',8,...
               'FontWeight','bold');
     uicontrol('Parent',d,...
               'Style','text',...
               'Position',[0 286 260 10],...
               'String','--------------------------------------',...
               'FontSize',8,...
               'FontWeight','bold');
     uicontrol('Parent',d,...
               'Style','text',...
               'Position',[10 260 260 20],...
               'String','File Address:',...
               'HorizontalAlignment','left');
location = uicontrol('Parent',d,...
               'Style','edit',...
               'Position',[10 245 170 20],...
               'String','5K_200s_3_4.wav',...
               'HorizontalAlignment','left',...
               'HorizontalAlignment','center');
           uicontrol('Parent',d,...
               'Position',[195 245 50 20],...
               'String','Browse',...
               'Callback',@Browse);
     uicontrol('Parent',d,...
               'Style','text',...
               'Position',[10 210 90 20],...
               'HorizontalAlignment','left',...
               'String','Link Frequency:');
     edt1 = uicontrol('Parent',d,...
               'Style','edit',...
               'Position',[100 213 150 20],...
               'String','5e3',...
               'HorizontalAlignment','left',...
               'HorizontalAlignment','center');
     uicontrol('Parent',d,...
               'Style','text',...
               'Position',[10 185 90 20],...
               'HorizontalAlignment','left',...
               'String','SymbolRate:');
     edt2 = uicontrol('Parent',d,...
               'Style','edit',...
               'Position',[100 188 150 20],...
               'String','200');
     uicontrol('Parent',d,...
               'Style','text',...
               'Position',[10 160 90 20],...
               'HorizontalAlignment','left',...
               'String','FEC:');
     edt3 = uicontrol('Parent',d,...
               'Style','edit',...
               'Position',[100 163 150 20],...
               'String','3/4');
     txt5 = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[10 120 200 20],...
               'HorizontalAlignment','left',...
               'FontWeight','bold',...
               'String','Demodulator:');
     popup = uicontrol('Parent',d,...
               'Style','popup',...
               'String',{'DFE-RLS';'DFE-LMS';'Viterbi-No Equalizer'},...
               'Position',[100 123 150 20],...
               'Callback',@popup_callback);
     txt5 = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[10 85 60 20],...
               'HorizontalAlignment','left',...
               'String','Forgeting:',...
               'Visible','on');
     edt4 = uicontrol('Parent',d,...
               'Style','edit',...
               'Position',[60 88 50 20],...
               'String','1',...
               'Visible','on');
     txt6 = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[120 85 60 20],...
               'HorizontalAlignment','left',...
               'String','CovMatrix: ',...
               'Visible','on');
     edt5 = uicontrol('Parent',d,...
               'Style','edit',...
               'Position',[175 88 50 20],...
               'String','1000',...
               'Visible','on');
     txt7 = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[10 85 50 20],...
               'HorizontalAlignment','left',...
               'String','Lambda: ',...
               'Visible','off');
     edt6 = uicontrol('Parent',d,...
               'Style','edit',...
               'Position',[60 88 50 20],...
               'String','0.005',...
               'Visible','off');
     txt8 = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[10 55 125 20],...
               'HorizontalAlignment','left',...
               'String','Weights (Fwd,Bwd) :',...
               'Visible','on');
     edt7 = uicontrol('Parent',d,...
               'Style','edit',...
               'Position',[120 58 130 20],...
               'String','[50,50]',...
               'Visible','on');
      uicontrol('Parent',d,...
           'Position',[185 10 70 25],...
           'String','Close',...
           'Callback',@Close);
      uicontrol('Parent',d,...
           'Position',[110 10 70 25],...
           'String','Ok',...
           'Callback',@pressOk);
       uiwait(d);
       
      function popup_callback(popup,~)
          if popup.Value==1
              txt5.Visible='on';
              edt4.Visible='on';
              txt6.Visible='on';
              edt5.Visible='on';
              txt7.Visible='off';
              edt6.Visible='off';
          elseif popup.Value==2
              txt5.Visible='off';
              edt4.Visible='off';
              txt6.Visible='off';
              edt5.Visible='off';
              txt7.Visible='on';
              edt6.Visible='on';
              txt8.Visible='on';
              edt7.Visible='on';
          elseif popup.Value==3
              txt5.Visible='off';
              edt4.Visible='off';
              txt6.Visible='off';
              edt5.Visible='off';
              txt7.Visible='off';
              edt6.Visible='off';
              txt8.Visible='off';
              edt7.Visible='off';
          end  
      end
    function pressOk(~,~)
        if ~(strcmp(edt3.String,'1/2') || strcmp(edt3.String,'3/4') || strcmp(edt3.String,'5/6'))
              msgbox('desired FEC CodeRate is not supported','Error','error')
        elseif ~(str2double(edt1.String)<18e3 && str2double(edt1.String)>2e3 )
              msgbox('Center Frequency range must be within 2-18 KHz ','Error','warn')
        elseif str2double(edt2.String)>1e3
              msgbox('Symbol Rate must be Less than 1Ks/s ','Error','warn')
        else
            FEC=edt3.String;
            CenterFreq=str2double(edt1.String);
            SymbolRate=str2double(edt2.String);
            FEC=edt3.String;
            DemodMod=popup.Value;
            if popup.Value==1
                constant1=str2double(edt4.String);
                constant2=str2double(edt5.String);
                nfwdweights=str2num(edt7.String);
                nfbkweights=nfwdweights(2);
                nfwdweights=nfwdweights(1);
            elseif popup.Value==2
                constant1=str2double(edt6.String);
                constant2=[];
                nfwdweights=str2num(edt7.String);
                nfbkweights=nfwdweights(2);
                nfwdweights=nfwdweights(1);
            elseif popup.Value==3
                constant1=[];
                constant2=[];
                nfwdweights=[];
                nfbkweights=[];
            end
            path=location.String;
            delete(gcf)
        end
    end
    function Close(~,~)
        delete(gcf)
        msgbox('you cancelled the proccess','STOP','warn');
    end
    function Browse(~,~)
        [a,location.String] = uigetfile({'*.wav;*.m4a'});
        location.String=[location.String,a];
    end
end
     